name: PR Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: install py
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: pyscript
        id: pyscript
        run: |
          python3 scripts/test.py
          
      - name: test
        run: |
          echo "::add-mask::${{ steps.pyscript.outputs.key }}"
          echo ${{ steps.pyscript.outputs.key }}

      - name: Get PR Number
        run: |
          # Extract PR number from the merge commit message
          PR_NUMBER=$(git log -n 1 | grep -oE '#[0-9]+' | sed 's/#//')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "${{ github.event.repository.name }}"
          echo "${{ github.repository }}"

      - name: Get PR Description
        run: |
          # Retrieve PR description using GitHub API
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.body')
          echo "PR Description: $PR_DESCRIPTION"
