name: PR Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Configure AWS Credentials and Assume Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: install expect
        run: |
          sudo apt install -y expect
          sudo apt update
          
      - name: Start a SSM session
        run: |
          unbuffer aws ssm start-session --target "${{ secrets.AWS_INSTANCE_ID }}" --region us-west-2
          
      - name: test
        run: |
          ls
          hostname
          pwd
          whoami

      - name: Get PR Number
        run: |
          # Extract PR number from the merge commit message
          PR_NUMBER=$(git log -n 1 | grep -oE '#[0-9]+' | sed 's/#//')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "${{ github.event.repository.name }}"
          echo "${{ github.repository }}"

      - name: Get PR Description
        run: |
          # Retrieve PR description using GitHub API
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.body')
          echo "PR Description: $PR_DESCRIPTION"
