name: Update Other Repository
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['Splunk/Detections/sec/local/savedsearches.conf']

jobs:
  update-code-in-other-repo:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Git Clone current repository
        uses: actions/checkout@v3
 
      - name: Clone splunk repository
        run: |
          cd ../..
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://github.com/objectbased/aws-testing.git
          cd aws-testing
          git remote set-url origin "https://objectbased:${{ secrets.ACCESS_TOKEN }}@github.com/objectbased/aws-testing.git"
          
      - name: Get pull request number from detections repository
        run: |
          PR_NUMBER=$(git log -n 1 | grep -oE '#[0-9]+' | sed 's/#//')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Get pull request description
        run: |
          PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.body')
          PR_TITLE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.title')
          echo "PR Title: $PR_TITLE"
          echo "PR Description: $PR_DESCRIPTION"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          #echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV

          echo "PR_DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$PR_DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "$PR_DESCRIPTION"
          
      - name: Copy file to other repository
        run: |
          pwd
          rsync -av --delete-after Splunk/Detections/sec/local/savedsearches.conf /home/runner/work/aws-testing/shcluster/apps/sec/local/savedsearches.conf
          
      - name: Set branch name and vars
        run: |
          echo "feature_branch_name=cyber-$(date +"%Y-%m-%d-%H-%M")-${{ github.sha }}" >> $GITHUB_ENV
          
      - name: Commit changes to splunk repository
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
        run: |
          cd ../../aws-testing
          git checkout -b $FEATURE_BRANCH_NAME
          git add .
          git commit -m "$PR_DESCRIPTION"
          git push origin $FEATURE_BRANCH_NAME
          
      - name: Open pull request
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/objectbased/aws-testing/pulls \
            -d "{\"title\": \"$PR_TITLE\", \"body\": \"Description:\\n\\n$PR_DESCRIPTION\\n\\nCheck pull request here: https://github.com/objectbased/synctesting/pull/$PR_NUMBER\", \"head\": \"$FEATURE_BRANCH_NAME\", \"base\": \"main\"}"
            